### ISSUE TITLE
"Chroma" Animated Crosshair Invisible Frames

### ISSUE THREAD

**Issue by Snuggle** [bugfroggy/AnimatedCursor#2]
The Chroma crosshair disappears for some reason if you set these settings:

Scale: `1`
Framerate: `30`
Frame Count: `60`

For some reason, if the frame count is above ~15 some frames become invisible as if the rainbow isn't properly looped.

**Comment by robere2** [comment]
There are only 15 frames in the `CHROMA_PLUS` crosshair:
[chroma_plus.png](https://bugg.co/i/?i=5a1459e96a4af&lg=1)
Therefore extending the frame count beyond the total frames in the image file will result in the mod trying to render frames that are empty. In the future might modify `CHROMA_PLUS` to have 180 frames so you can slow it down while still maintaining a smooth framerate, but for now this is not considered a bug.
